context("Check for classes")

test_that("Existence check for all classes corresponding to each protobuf model", {
  expect_true(isClass(factset.protobuf.stach.Package))
  expect_true(isClass(factset.protobuf.stach.MetadataItem))

  expect_true(isClass(factset.protobuf.stach.table.DataType))
  expect_true(isClass(factset.protobuf.stach.table.HorizontalAlignment))
  expect_true(isClass(factset.protobuf.stach.table.ListOfMetadata))
  expect_true(isClass(factset.protobuf.stach.table.MetadataCollection))
  expect_true(isClass(factset.protobuf.stach.table.MetadataLocations))
  expect_true(isClass(factset.protobuf.stach.table.Reference))
  expect_true(isClass(factset.protobuf.stach.table.ReferenceFilterMode))
  expect_true(isClass(factset.protobuf.stach.table.ReferenceType))
  expect_true(isClass(factset.protobuf.stach.table.SeriesData))
  expect_true(isClass(factset.protobuf.stach.table.SeriesDefinition))
  expect_true(isClass(factset.protobuf.stach.table.SeriesFormat))
  expect_true(isClass(factset.protobuf.stach.table.Table))
  expect_true(isClass(factset.protobuf.stach.table.TableData))
  expect_true(isClass(factset.protobuf.stach.table.TableDefinition))
  expect_true(isClass(factset.protobuf.stach.table.VerticalAlignment))

  expect_true(isClass(factset.protobuf.stach.table.DoubleArray))
  expect_true(isClass(factset.protobuf.stach.table.FloatArray))
  expect_true(isClass(factset.protobuf.stach.table.Int32Array))
  expect_true(isClass(factset.protobuf.stach.table.Int64Array))
  expect_true(isClass(factset.protobuf.stach.table.BoolArray))
  expect_true(isClass(factset.protobuf.stach.table.StringArray))
  expect_true(isClass(factset.protobuf.stach.table.DurationArray))
  expect_true(isClass(factset.protobuf.stach.table.TimestampArray))
  
  expect_true(is.R6Class(factset.protobuf.stach.NullValues))
})