nodeLinker: node-modules

npmRegistryServer: "http://artifactory.factset.com/artifactory/api/npm/npm/"

npmScopes:
  fds:
    npmRegistryServer: "http://artifactory.factset.com/artifactory/api/npm/npm-fds/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

unsafeHttpWhitelist: artifactory.factset.com

yarnPath: .yarn/releases/yarn-2.1.1.cjs
