// source: fds/protobuf/stach/table/Table.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var fds_protobuf_stach_table_TableData_pb = require('../../../../fds/protobuf/stach/table/TableData_pb.js');
goog.object.extend(proto, fds_protobuf_stach_table_TableData_pb);
var fds_protobuf_stach_table_TableDefinition_pb = require('../../../../fds/protobuf/stach/table/TableDefinition_pb.js');
goog.object.extend(proto, fds_protobuf_stach_table_TableDefinition_pb);
goog.exportSymbol('proto.factset.protobuf.stach.table.Table', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.factset.protobuf.stach.table.Table = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.factset.protobuf.stach.table.Table, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.factset.protobuf.stach.table.Table.displayName = 'proto.factset.protobuf.stach.table.Table';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.factset.protobuf.stach.table.Table.prototype.toObject = function(opt_includeInstance) {
  return proto.factset.protobuf.stach.table.Table.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.factset.protobuf.stach.table.Table} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.factset.protobuf.stach.table.Table.toObject = function(includeInstance, msg) {
  var f, obj = {
    definition: (f = msg.getDefinition()) && fds_protobuf_stach_table_TableDefinition_pb.TableDefinition.toObject(includeInstance, f),
    data: (f = msg.getData()) && fds_protobuf_stach_table_TableData_pb.TableData.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.factset.protobuf.stach.table.Table}
 */
proto.factset.protobuf.stach.table.Table.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.factset.protobuf.stach.table.Table;
  return proto.factset.protobuf.stach.table.Table.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.factset.protobuf.stach.table.Table} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.factset.protobuf.stach.table.Table}
 */
proto.factset.protobuf.stach.table.Table.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new fds_protobuf_stach_table_TableDefinition_pb.TableDefinition;
      reader.readMessage(value,fds_protobuf_stach_table_TableDefinition_pb.TableDefinition.deserializeBinaryFromReader);
      msg.setDefinition(value);
      break;
    case 2:
      var value = new fds_protobuf_stach_table_TableData_pb.TableData;
      reader.readMessage(value,fds_protobuf_stach_table_TableData_pb.TableData.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.factset.protobuf.stach.table.Table.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.factset.protobuf.stach.table.Table.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.factset.protobuf.stach.table.Table} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.factset.protobuf.stach.table.Table.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDefinition();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      fds_protobuf_stach_table_TableDefinition_pb.TableDefinition.serializeBinaryToWriter
    );
  }
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      fds_protobuf_stach_table_TableData_pb.TableData.serializeBinaryToWriter
    );
  }
};


/**
 * optional TableDefinition definition = 1;
 * @return {?proto.factset.protobuf.stach.table.TableDefinition}
 */
proto.factset.protobuf.stach.table.Table.prototype.getDefinition = function() {
  return /** @type{?proto.factset.protobuf.stach.table.TableDefinition} */ (
    jspb.Message.getWrapperField(this, fds_protobuf_stach_table_TableDefinition_pb.TableDefinition, 1));
};


/**
 * @param {?proto.factset.protobuf.stach.table.TableDefinition|undefined} value
 * @return {!proto.factset.protobuf.stach.table.Table} returns this
*/
proto.factset.protobuf.stach.table.Table.prototype.setDefinition = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.factset.protobuf.stach.table.Table} returns this
 */
proto.factset.protobuf.stach.table.Table.prototype.clearDefinition = function() {
  return this.setDefinition(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.factset.protobuf.stach.table.Table.prototype.hasDefinition = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional TableData data = 2;
 * @return {?proto.factset.protobuf.stach.table.TableData}
 */
proto.factset.protobuf.stach.table.Table.prototype.getData = function() {
  return /** @type{?proto.factset.protobuf.stach.table.TableData} */ (
    jspb.Message.getWrapperField(this, fds_protobuf_stach_table_TableData_pb.TableData, 2));
};


/**
 * @param {?proto.factset.protobuf.stach.table.TableData|undefined} value
 * @return {!proto.factset.protobuf.stach.table.Table} returns this
*/
proto.factset.protobuf.stach.table.Table.prototype.setData = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.factset.protobuf.stach.table.Table} returns this
 */
proto.factset.protobuf.stach.table.Table.prototype.clearData = function() {
  return this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.factset.protobuf.stach.table.Table.prototype.hasData = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.factset.protobuf.stach.table);
