// source: fds/protobuf/stach/table/TableDefinition.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var fds_protobuf_stach_table_ColumnDefinition_pb = require('../../../../fds/protobuf/stach/table/ColumnDefinition_pb.js');
goog.object.extend(proto, fds_protobuf_stach_table_ColumnDefinition_pb);
goog.exportSymbol('proto.factset.protobuf.stach.table.TableDefinition', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.factset.protobuf.stach.table.TableDefinition = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.factset.protobuf.stach.table.TableDefinition.repeatedFields_, null);
};
goog.inherits(proto.factset.protobuf.stach.table.TableDefinition, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.factset.protobuf.stach.table.TableDefinition.displayName = 'proto.factset.protobuf.stach.table.TableDefinition';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.factset.protobuf.stach.table.TableDefinition.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.factset.protobuf.stach.table.TableDefinition.prototype.toObject = function(opt_includeInstance) {
  return proto.factset.protobuf.stach.table.TableDefinition.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.factset.protobuf.stach.table.TableDefinition} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.factset.protobuf.stach.table.TableDefinition.toObject = function(includeInstance, msg) {
  var f, obj = {
    headerTableId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    columnsList: jspb.Message.toObjectList(msg.getColumnsList(),
    fds_protobuf_stach_table_ColumnDefinition_pb.ColumnDefinition.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.factset.protobuf.stach.table.TableDefinition}
 */
proto.factset.protobuf.stach.table.TableDefinition.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.factset.protobuf.stach.table.TableDefinition;
  return proto.factset.protobuf.stach.table.TableDefinition.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.factset.protobuf.stach.table.TableDefinition} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.factset.protobuf.stach.table.TableDefinition}
 */
proto.factset.protobuf.stach.table.TableDefinition.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setHeaderTableId(value);
      break;
    case 2:
      var value = new fds_protobuf_stach_table_ColumnDefinition_pb.ColumnDefinition;
      reader.readMessage(value,fds_protobuf_stach_table_ColumnDefinition_pb.ColumnDefinition.deserializeBinaryFromReader);
      msg.addColumns(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.factset.protobuf.stach.table.TableDefinition.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.factset.protobuf.stach.table.TableDefinition.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.factset.protobuf.stach.table.TableDefinition} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.factset.protobuf.stach.table.TableDefinition.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeaderTableId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getColumnsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      fds_protobuf_stach_table_ColumnDefinition_pb.ColumnDefinition.serializeBinaryToWriter
    );
  }
};


/**
 * optional string header_table_id = 1;
 * @return {string}
 */
proto.factset.protobuf.stach.table.TableDefinition.prototype.getHeaderTableId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.factset.protobuf.stach.table.TableDefinition} returns this
 */
proto.factset.protobuf.stach.table.TableDefinition.prototype.setHeaderTableId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated ColumnDefinition columns = 2;
 * @return {!Array<!proto.factset.protobuf.stach.table.ColumnDefinition>}
 */
proto.factset.protobuf.stach.table.TableDefinition.prototype.getColumnsList = function() {
  return /** @type{!Array<!proto.factset.protobuf.stach.table.ColumnDefinition>} */ (
    jspb.Message.getRepeatedWrapperField(this, fds_protobuf_stach_table_ColumnDefinition_pb.ColumnDefinition, 2));
};


/**
 * @param {!Array<!proto.factset.protobuf.stach.table.ColumnDefinition>} value
 * @return {!proto.factset.protobuf.stach.table.TableDefinition} returns this
*/
proto.factset.protobuf.stach.table.TableDefinition.prototype.setColumnsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.factset.protobuf.stach.table.ColumnDefinition=} opt_value
 * @param {number=} opt_index
 * @return {!proto.factset.protobuf.stach.table.ColumnDefinition}
 */
proto.factset.protobuf.stach.table.TableDefinition.prototype.addColumns = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.factset.protobuf.stach.table.ColumnDefinition, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.factset.protobuf.stach.table.TableDefinition} returns this
 */
proto.factset.protobuf.stach.table.TableDefinition.prototype.clearColumnsList = function() {
  return this.setColumnsList([]);
};


goog.object.extend(exports, proto.factset.protobuf.stach.table);
