# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fds/protobuf/stach/table/ColumnData.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from fds.protobuf.stach.table import CellDefinition_pb2 as fds_dot_protobuf_dot_stach_dot_table_dot_CellDefinition__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='fds/protobuf/stach/table/ColumnData.proto',
  package='factset.protobuf.stach.table',
  syntax='proto3',
  serialized_options=b'\n com.factset.protobuf.stach.tableB\017ColumnDataProtoZ=github.com/factset/stachschema/go/v2/fds/protobuf/stach/table\252\002\034FactSet.Protobuf.Stach.Table',
  serialized_pb=b'\n)fds/protobuf/stach/table/ColumnData.proto\x12\x1c\x66\x61\x63tset.protobuf.stach.table\x1a-fds/protobuf/stach/table/CellDefinition.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xf0\x01\n\nColumnData\x12\x44\n\x06ranges\x18\x01 \x03(\x0b\x32\x34.factset.protobuf.stach.table.ColumnData.RangesEntry\x12*\n\x06values\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.ListValue\x12\x41\n\x0b\x64\x65\x66initions\x18\x03 \x03(\x0b\x32,.factset.protobuf.stach.table.CellDefinition\x1a-\n\x0bRangesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x42\x91\x01\n com.factset.protobuf.stach.tableB\x0f\x43olumnDataProtoZ=github.com/factset/stachschema/go/v2/fds/protobuf/stach/table\xaa\x02\x1c\x46\x61\x63tSet.Protobuf.Stach.Tableb\x06proto3'
  ,
  dependencies=[fds_dot_protobuf_dot_stach_dot_table_dot_CellDefinition__pb2.DESCRIPTOR,google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_COLUMNDATA_RANGESENTRY = _descriptor.Descriptor(
  name='RangesEntry',
  full_name='factset.protobuf.stach.table.ColumnData.RangesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='factset.protobuf.stach.table.ColumnData.RangesEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='factset.protobuf.stach.table.ColumnData.RangesEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=348,
  serialized_end=393,
)

_COLUMNDATA = _descriptor.Descriptor(
  name='ColumnData',
  full_name='factset.protobuf.stach.table.ColumnData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ranges', full_name='factset.protobuf.stach.table.ColumnData.ranges', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='factset.protobuf.stach.table.ColumnData.values', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='definitions', full_name='factset.protobuf.stach.table.ColumnData.definitions', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_COLUMNDATA_RANGESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=393,
)

_COLUMNDATA_RANGESENTRY.containing_type = _COLUMNDATA
_COLUMNDATA.fields_by_name['ranges'].message_type = _COLUMNDATA_RANGESENTRY
_COLUMNDATA.fields_by_name['values'].message_type = google_dot_protobuf_dot_struct__pb2._LISTVALUE
_COLUMNDATA.fields_by_name['definitions'].message_type = fds_dot_protobuf_dot_stach_dot_table_dot_CellDefinition__pb2._CELLDEFINITION
DESCRIPTOR.message_types_by_name['ColumnData'] = _COLUMNDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ColumnData = _reflection.GeneratedProtocolMessageType('ColumnData', (_message.Message,), {

  'RangesEntry' : _reflection.GeneratedProtocolMessageType('RangesEntry', (_message.Message,), {
    'DESCRIPTOR' : _COLUMNDATA_RANGESENTRY,
    '__module__' : 'fds.protobuf.stach.table.ColumnData_pb2'
    # @@protoc_insertion_point(class_scope:factset.protobuf.stach.table.ColumnData.RangesEntry)
    })
  ,
  'DESCRIPTOR' : _COLUMNDATA,
  '__module__' : 'fds.protobuf.stach.table.ColumnData_pb2'
  # @@protoc_insertion_point(class_scope:factset.protobuf.stach.table.ColumnData)
  })
_sym_db.RegisterMessage(ColumnData)
_sym_db.RegisterMessage(ColumnData.RangesEntry)


DESCRIPTOR._options = None
_COLUMNDATA_RANGESENTRY._options = None
# @@protoc_insertion_point(module_scope)
