# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fds/protobuf/stach/table/MetadataCollection.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from fds.protobuf.stach.table import MetadataItem_pb2 as fds_dot_protobuf_dot_stach_dot_table_dot_MetadataItem__pb2
from fds.protobuf.stach.table import MetadataLocations_pb2 as fds_dot_protobuf_dot_stach_dot_table_dot_MetadataLocations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='fds/protobuf/stach/table/MetadataCollection.proto',
  package='factset.protobuf.stach.table',
  syntax='proto3',
  serialized_options=b'\n com.factset.protobuf.stach.tableB\027MetadataCollectionProtoZ=github.com/factset/stachschema/go/v2/fds/protobuf/stach/table\252\002\034FactSet.Protobuf.Stach.Table',
  serialized_pb=b'\n1fds/protobuf/stach/table/MetadataCollection.proto\x12\x1c\x66\x61\x63tset.protobuf.stach.table\x1a+fds/protobuf/stach/table/MetadataItem.proto\x1a\x30\x66\x64s/protobuf/stach/table/MetadataLocations.proto\"\xfe\x01\n\x12MetadataCollection\x12J\n\x05items\x18\x01 \x03(\x0b\x32;.factset.protobuf.stach.table.MetadataCollection.ItemsEntry\x12\x42\n\tlocations\x18\x02 \x01(\x0b\x32/.factset.protobuf.stach.table.MetadataLocations\x1aX\n\nItemsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x39\n\x05value\x18\x02 \x01(\x0b\x32*.factset.protobuf.stach.table.MetadataItem:\x02\x38\x01\x42\x99\x01\n com.factset.protobuf.stach.tableB\x17MetadataCollectionProtoZ=github.com/factset/stachschema/go/v2/fds/protobuf/stach/table\xaa\x02\x1c\x46\x61\x63tSet.Protobuf.Stach.Tableb\x06proto3'
  ,
  dependencies=[fds_dot_protobuf_dot_stach_dot_table_dot_MetadataItem__pb2.DESCRIPTOR,fds_dot_protobuf_dot_stach_dot_table_dot_MetadataLocations__pb2.DESCRIPTOR,])




_METADATACOLLECTION_ITEMSENTRY = _descriptor.Descriptor(
  name='ItemsEntry',
  full_name='factset.protobuf.stach.table.MetadataCollection.ItemsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='factset.protobuf.stach.table.MetadataCollection.ItemsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='factset.protobuf.stach.table.MetadataCollection.ItemsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=345,
  serialized_end=433,
)

_METADATACOLLECTION = _descriptor.Descriptor(
  name='MetadataCollection',
  full_name='factset.protobuf.stach.table.MetadataCollection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='factset.protobuf.stach.table.MetadataCollection.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='locations', full_name='factset.protobuf.stach.table.MetadataCollection.locations', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_METADATACOLLECTION_ITEMSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=433,
)

_METADATACOLLECTION_ITEMSENTRY.fields_by_name['value'].message_type = fds_dot_protobuf_dot_stach_dot_table_dot_MetadataItem__pb2._METADATAITEM
_METADATACOLLECTION_ITEMSENTRY.containing_type = _METADATACOLLECTION
_METADATACOLLECTION.fields_by_name['items'].message_type = _METADATACOLLECTION_ITEMSENTRY
_METADATACOLLECTION.fields_by_name['locations'].message_type = fds_dot_protobuf_dot_stach_dot_table_dot_MetadataLocations__pb2._METADATALOCATIONS
DESCRIPTOR.message_types_by_name['MetadataCollection'] = _METADATACOLLECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MetadataCollection = _reflection.GeneratedProtocolMessageType('MetadataCollection', (_message.Message,), {

  'ItemsEntry' : _reflection.GeneratedProtocolMessageType('ItemsEntry', (_message.Message,), {
    'DESCRIPTOR' : _METADATACOLLECTION_ITEMSENTRY,
    '__module__' : 'fds.protobuf.stach.table.MetadataCollection_pb2'
    # @@protoc_insertion_point(class_scope:factset.protobuf.stach.table.MetadataCollection.ItemsEntry)
    })
  ,
  'DESCRIPTOR' : _METADATACOLLECTION,
  '__module__' : 'fds.protobuf.stach.table.MetadataCollection_pb2'
  # @@protoc_insertion_point(class_scope:factset.protobuf.stach.table.MetadataCollection)
  })
_sym_db.RegisterMessage(MetadataCollection)
_sym_db.RegisterMessage(MetadataCollection.ItemsEntry)


DESCRIPTOR._options = None
_METADATACOLLECTION_ITEMSENTRY._options = None
# @@protoc_insertion_point(module_scope)
