# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fds/protobuf/stach/table/SeriesDefinition.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from fds.protobuf.stach.table import DataType_pb2 as fds_dot_protobuf_dot_stach_dot_table_dot_DataType__pb2
from fds.protobuf.stach.table import SeriesFormat_pb2 as fds_dot_protobuf_dot_stach_dot_table_dot_SeriesFormat__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='fds/protobuf/stach/table/SeriesDefinition.proto',
  package='factset.protobuf.stach.table',
  syntax='proto3',
  serialized_options=_b('\n com.factset.protobuf.stach.tableB\025SeriesDefinitionProto\252\002\034FactSet.Protobuf.Stach.Table'),
  serialized_pb=_b('\n/fds/protobuf/stach/table/SeriesDefinition.proto\x12\x1c\x66\x61\x63tset.protobuf.stach.table\x1a\'fds/protobuf/stach/table/DataType.proto\x1a+fds/protobuf/stach/table/SeriesFormat.proto\"\xaf\x02\n\x10SeriesDefinition\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x34\n\x04type\x18\x04 \x01(\x0e\x32&.factset.protobuf.stach.table.DataType\x12\x14\n\x0cis_dimension\x18\x05 \x01(\x08\x12\x11\n\tis_hidden\x18\x06 \x01(\x08\x12\x17\n\x0fnext_sibling_id\x18\x07 \x01(\t\x12\x11\n\tparent_id\x18\x08 \x01(\t\x12\x11\n\theader_id\x18\t \x01(\t\x12:\n\x06\x66ormat\x18\x0b \x01(\x0b\x32*.factset.protobuf.stach.table.SeriesFormatJ\x04\x08\n\x10\x0bR\x0cheader_indexBX\n com.factset.protobuf.stach.tableB\x15SeriesDefinitionProto\xaa\x02\x1c\x46\x61\x63tSet.Protobuf.Stach.Tableb\x06proto3')
  ,
  dependencies=[fds_dot_protobuf_dot_stach_dot_table_dot_DataType__pb2.DESCRIPTOR,fds_dot_protobuf_dot_stach_dot_table_dot_SeriesFormat__pb2.DESCRIPTOR,])




_SERIESDEFINITION = _descriptor.Descriptor(
  name='SeriesDefinition',
  full_name='factset.protobuf.stach.table.SeriesDefinition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='factset.protobuf.stach.table.SeriesDefinition.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='factset.protobuf.stach.table.SeriesDefinition.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='factset.protobuf.stach.table.SeriesDefinition.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='factset.protobuf.stach.table.SeriesDefinition.type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_dimension', full_name='factset.protobuf.stach.table.SeriesDefinition.is_dimension', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_hidden', full_name='factset.protobuf.stach.table.SeriesDefinition.is_hidden', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='next_sibling_id', full_name='factset.protobuf.stach.table.SeriesDefinition.next_sibling_id', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parent_id', full_name='factset.protobuf.stach.table.SeriesDefinition.parent_id', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='header_id', full_name='factset.protobuf.stach.table.SeriesDefinition.header_id', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='format', full_name='factset.protobuf.stach.table.SeriesDefinition.format', index=9,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=471,
)

_SERIESDEFINITION.fields_by_name['type'].enum_type = fds_dot_protobuf_dot_stach_dot_table_dot_DataType__pb2._DATATYPE
_SERIESDEFINITION.fields_by_name['format'].message_type = fds_dot_protobuf_dot_stach_dot_table_dot_SeriesFormat__pb2._SERIESFORMAT
DESCRIPTOR.message_types_by_name['SeriesDefinition'] = _SERIESDEFINITION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SeriesDefinition = _reflection.GeneratedProtocolMessageType('SeriesDefinition', (_message.Message,), {
  'DESCRIPTOR' : _SERIESDEFINITION,
  '__module__' : 'fds.protobuf.stach.table.SeriesDefinition_pb2'
  # @@protoc_insertion_point(class_scope:factset.protobuf.stach.table.SeriesDefinition)
  })
_sym_db.RegisterMessage(SeriesDefinition)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
