# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fds/protobuf/stach/table/SeriesData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from fds.protobuf.stach.table import Wrappers_pb2 as fds_dot_protobuf_dot_stach_dot_table_dot_Wrappers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='fds/protobuf/stach/table/SeriesData.proto',
  package='factset.protobuf.stach.table',
  syntax='proto3',
  serialized_options=_b('\n com.factset.protobuf.stach.tableB\017SeriesDataProto\252\002\034FactSet.Protobuf.Stach.Table'),
  serialized_pb=_b('\n)fds/protobuf/stach/table/SeriesData.proto\x12\x1c\x66\x61\x63tset.protobuf.stach.table\x1a\'fds/protobuf/stach/table/Wrappers.proto\"\xc9\x05\n\nSeriesData\x12\x44\n\x06ranges\x18\x01 \x03(\x0b\x32\x34.factset.protobuf.stach.table.SeriesData.RangesEntry\x12\x41\n\x0c\x64ouble_array\x18\x64 \x01(\x0b\x32).factset.protobuf.stach.table.DoubleArrayH\x00\x12?\n\x0b\x66loat_array\x18\x65 \x01(\x0b\x32(.factset.protobuf.stach.table.FloatArrayH\x00\x12?\n\x0bint32_array\x18\x66 \x01(\x0b\x32(.factset.protobuf.stach.table.Int32ArrayH\x00\x12?\n\x0bint64_array\x18g \x01(\x0b\x32(.factset.protobuf.stach.table.Int64ArrayH\x00\x12=\n\nbool_array\x18j \x01(\x0b\x32\'.factset.protobuf.stach.table.BoolArrayH\x00\x12\x41\n\x0cstring_array\x18k \x01(\x0b\x32).factset.protobuf.stach.table.StringArrayH\x00\x12\x45\n\x0e\x64uration_array\x18l \x01(\x0b\x32+.factset.protobuf.stach.table.DurationArrayH\x00\x12G\n\x0ftimestamp_array\x18m \x01(\x0b\x32,.factset.protobuf.stach.table.TimestampArrayH\x00\x1a-\n\x0bRangesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x42\x06\n\x04\x64\x61taJ\x04\x08h\x10iJ\x04\x08i\x10jR\x0cuint32_arrayR\x0cuint64_arrayBR\n com.factset.protobuf.stach.tableB\x0fSeriesDataProto\xaa\x02\x1c\x46\x61\x63tSet.Protobuf.Stach.Tableb\x06proto3')
  ,
  dependencies=[fds_dot_protobuf_dot_stach_dot_table_dot_Wrappers__pb2.DESCRIPTOR,])




_SERIESDATA_RANGESENTRY = _descriptor.Descriptor(
  name='RangesEntry',
  full_name='factset.protobuf.stach.table.SeriesData.RangesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='factset.protobuf.stach.table.SeriesData.RangesEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='factset.protobuf.stach.table.SeriesData.RangesEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=737,
  serialized_end=782,
)

_SERIESDATA = _descriptor.Descriptor(
  name='SeriesData',
  full_name='factset.protobuf.stach.table.SeriesData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ranges', full_name='factset.protobuf.stach.table.SeriesData.ranges', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='double_array', full_name='factset.protobuf.stach.table.SeriesData.double_array', index=1,
      number=100, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='float_array', full_name='factset.protobuf.stach.table.SeriesData.float_array', index=2,
      number=101, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='int32_array', full_name='factset.protobuf.stach.table.SeriesData.int32_array', index=3,
      number=102, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='int64_array', full_name='factset.protobuf.stach.table.SeriesData.int64_array', index=4,
      number=103, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bool_array', full_name='factset.protobuf.stach.table.SeriesData.bool_array', index=5,
      number=106, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='string_array', full_name='factset.protobuf.stach.table.SeriesData.string_array', index=6,
      number=107, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='duration_array', full_name='factset.protobuf.stach.table.SeriesData.duration_array', index=7,
      number=108, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp_array', full_name='factset.protobuf.stach.table.SeriesData.timestamp_array', index=8,
      number=109, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SERIESDATA_RANGESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='factset.protobuf.stach.table.SeriesData.data',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=117,
  serialized_end=830,
)

_SERIESDATA_RANGESENTRY.containing_type = _SERIESDATA
_SERIESDATA.fields_by_name['ranges'].message_type = _SERIESDATA_RANGESENTRY
_SERIESDATA.fields_by_name['double_array'].message_type = fds_dot_protobuf_dot_stach_dot_table_dot_Wrappers__pb2._DOUBLEARRAY
_SERIESDATA.fields_by_name['float_array'].message_type = fds_dot_protobuf_dot_stach_dot_table_dot_Wrappers__pb2._FLOATARRAY
_SERIESDATA.fields_by_name['int32_array'].message_type = fds_dot_protobuf_dot_stach_dot_table_dot_Wrappers__pb2._INT32ARRAY
_SERIESDATA.fields_by_name['int64_array'].message_type = fds_dot_protobuf_dot_stach_dot_table_dot_Wrappers__pb2._INT64ARRAY
_SERIESDATA.fields_by_name['bool_array'].message_type = fds_dot_protobuf_dot_stach_dot_table_dot_Wrappers__pb2._BOOLARRAY
_SERIESDATA.fields_by_name['string_array'].message_type = fds_dot_protobuf_dot_stach_dot_table_dot_Wrappers__pb2._STRINGARRAY
_SERIESDATA.fields_by_name['duration_array'].message_type = fds_dot_protobuf_dot_stach_dot_table_dot_Wrappers__pb2._DURATIONARRAY
_SERIESDATA.fields_by_name['timestamp_array'].message_type = fds_dot_protobuf_dot_stach_dot_table_dot_Wrappers__pb2._TIMESTAMPARRAY
_SERIESDATA.oneofs_by_name['data'].fields.append(
  _SERIESDATA.fields_by_name['double_array'])
_SERIESDATA.fields_by_name['double_array'].containing_oneof = _SERIESDATA.oneofs_by_name['data']
_SERIESDATA.oneofs_by_name['data'].fields.append(
  _SERIESDATA.fields_by_name['float_array'])
_SERIESDATA.fields_by_name['float_array'].containing_oneof = _SERIESDATA.oneofs_by_name['data']
_SERIESDATA.oneofs_by_name['data'].fields.append(
  _SERIESDATA.fields_by_name['int32_array'])
_SERIESDATA.fields_by_name['int32_array'].containing_oneof = _SERIESDATA.oneofs_by_name['data']
_SERIESDATA.oneofs_by_name['data'].fields.append(
  _SERIESDATA.fields_by_name['int64_array'])
_SERIESDATA.fields_by_name['int64_array'].containing_oneof = _SERIESDATA.oneofs_by_name['data']
_SERIESDATA.oneofs_by_name['data'].fields.append(
  _SERIESDATA.fields_by_name['bool_array'])
_SERIESDATA.fields_by_name['bool_array'].containing_oneof = _SERIESDATA.oneofs_by_name['data']
_SERIESDATA.oneofs_by_name['data'].fields.append(
  _SERIESDATA.fields_by_name['string_array'])
_SERIESDATA.fields_by_name['string_array'].containing_oneof = _SERIESDATA.oneofs_by_name['data']
_SERIESDATA.oneofs_by_name['data'].fields.append(
  _SERIESDATA.fields_by_name['duration_array'])
_SERIESDATA.fields_by_name['duration_array'].containing_oneof = _SERIESDATA.oneofs_by_name['data']
_SERIESDATA.oneofs_by_name['data'].fields.append(
  _SERIESDATA.fields_by_name['timestamp_array'])
_SERIESDATA.fields_by_name['timestamp_array'].containing_oneof = _SERIESDATA.oneofs_by_name['data']
DESCRIPTOR.message_types_by_name['SeriesData'] = _SERIESDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SeriesData = _reflection.GeneratedProtocolMessageType('SeriesData', (_message.Message,), dict(

  RangesEntry = _reflection.GeneratedProtocolMessageType('RangesEntry', (_message.Message,), dict(
    DESCRIPTOR = _SERIESDATA_RANGESENTRY,
    __module__ = 'fds.protobuf.stach.table.SeriesData_pb2'
    # @@protoc_insertion_point(class_scope:factset.protobuf.stach.table.SeriesData.RangesEntry)
    ))
  ,
  DESCRIPTOR = _SERIESDATA,
  __module__ = 'fds.protobuf.stach.table.SeriesData_pb2'
  # @@protoc_insertion_point(class_scope:factset.protobuf.stach.table.SeriesData)
  ))
_sym_db.RegisterMessage(SeriesData)
_sym_db.RegisterMessage(SeriesData.RangesEntry)


DESCRIPTOR._options = None
_SERIESDATA_RANGESENTRY._options = None
# @@protoc_insertion_point(module_scope)
