# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fds/protobuf/stach/table/Table.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from fds.protobuf.stach.table import TableData_pb2 as fds_dot_protobuf_dot_stach_dot_table_dot_TableData__pb2
from fds.protobuf.stach.table import TableDefinition_pb2 as fds_dot_protobuf_dot_stach_dot_table_dot_TableDefinition__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='fds/protobuf/stach/table/Table.proto',
  package='factset.protobuf.stach.table',
  syntax='proto3',
  serialized_options=_b('\n com.factset.protobuf.stach.tableB\nTableProto\252\002\034FactSet.Protobuf.Stach.Table'),
  serialized_pb=_b('\n$fds/protobuf/stach/table/Table.proto\x12\x1c\x66\x61\x63tset.protobuf.stach.table\x1a(fds/protobuf/stach/table/TableData.proto\x1a.fds/protobuf/stach/table/TableDefinition.proto\"\x81\x01\n\x05Table\x12\x41\n\ndefinition\x18\x01 \x01(\x0b\x32-.factset.protobuf.stach.table.TableDefinition\x12\x35\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\'.factset.protobuf.stach.table.TableDataBM\n com.factset.protobuf.stach.tableB\nTableProto\xaa\x02\x1c\x46\x61\x63tSet.Protobuf.Stach.Tableb\x06proto3')
  ,
  dependencies=[fds_dot_protobuf_dot_stach_dot_table_dot_TableData__pb2.DESCRIPTOR,fds_dot_protobuf_dot_stach_dot_table_dot_TableDefinition__pb2.DESCRIPTOR,])




_TABLE = _descriptor.Descriptor(
  name='Table',
  full_name='factset.protobuf.stach.table.Table',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='definition', full_name='factset.protobuf.stach.table.Table.definition', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='factset.protobuf.stach.table.Table.data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=290,
)

_TABLE.fields_by_name['definition'].message_type = fds_dot_protobuf_dot_stach_dot_table_dot_TableDefinition__pb2._TABLEDEFINITION
_TABLE.fields_by_name['data'].message_type = fds_dot_protobuf_dot_stach_dot_table_dot_TableData__pb2._TABLEDATA
DESCRIPTOR.message_types_by_name['Table'] = _TABLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Table = _reflection.GeneratedProtocolMessageType('Table', (_message.Message,), dict(
  DESCRIPTOR = _TABLE,
  __module__ = 'fds.protobuf.stach.table.Table_pb2'
  # @@protoc_insertion_point(class_scope:factset.protobuf.stach.table.Table)
  ))
_sym_db.RegisterMessage(Table)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
