// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: fds/protobuf/stach/v2/table/HorizontalAlignment.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace FactSet.Protobuf.Stach.V2.Table {

  /// <summary>Holder for reflection information generated from fds/protobuf/stach/v2/table/HorizontalAlignment.proto</summary>
  public static partial class HorizontalAlignmentReflection {

    #region Descriptor
    /// <summary>File descriptor for fds/protobuf/stach/v2/table/HorizontalAlignment.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static HorizontalAlignmentReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjVmZHMvcHJvdG9idWYvc3RhY2gvdjIvdGFibGUvSG9yaXpvbnRhbEFsaWdu",
            "bWVudC5wcm90bxIfZmFjdHNldC5wcm90b2J1Zi5zdGFjaC52Mi50YWJsZSpK",
            "ChNIb3Jpem9udGFsQWxpZ25tZW50EhIKDlVOS05PV05fSEFMSUdOEAASCAoE",
            "TEVGVBABEgoKBkNFTlRFUhACEgkKBVJJR0hUEANCoAEKI2NvbS5mYWN0c2V0",
            "LnByb3RvYnVmLnN0YWNoLnYyLnRhYmxlQhhIb3Jpem9udGFsQWxpZ25tZW50",
            "UHJvdG9aPWdpdGh1Yi5jb20vZmFjdHNldC9zdGFjaHNjaGVtYS9nby9mZHMv",
            "cHJvdG9idWYvc3RhY2gvdjIvdGFibGWqAh9GYWN0U2V0LlByb3RvYnVmLlN0",
            "YWNoLlYyLlRhYmxlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::FactSet.Protobuf.Stach.V2.Table.HorizontalAlignment), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// A horizontal alignment
  /// </summary>
  public enum HorizontalAlignment {
    /// <summary>
    /// This value should never be used, but exists to ensure that a value is specified
    /// </summary>
    [pbr::OriginalName("UNKNOWN_HALIGN")] UnknownHalign = 0,
    /// <summary>
    /// Value is horizontally aligned to the left of the cell
    /// </summary>
    [pbr::OriginalName("LEFT")] Left = 1,
    /// <summary>
    /// Value is horizontally aligned in the center of the cell
    /// </summary>
    [pbr::OriginalName("CENTER")] Center = 2,
    /// <summary>
    /// Value is horizontally aligned to the right of the cell
    /// </summary>
    [pbr::OriginalName("RIGHT")] Right = 3,
  }

  #endregion

}

#endregion Designer generated code
