// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: fds/protobuf/stach/v2/table/MetadataItem.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace FactSet.Protobuf.Stach.V2.Table {

  /// <summary>Holder for reflection information generated from fds/protobuf/stach/v2/table/MetadataItem.proto</summary>
  public static partial class MetadataItemReflection {

    #region Descriptor
    /// <summary>File descriptor for fds/protobuf/stach/v2/table/MetadataItem.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MetadataItemReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci5mZHMvcHJvdG9idWYvc3RhY2gvdjIvdGFibGUvTWV0YWRhdGFJdGVtLnBy",
            "b3RvEh9mYWN0c2V0LnByb3RvYnVmLnN0YWNoLnYyLnRhYmxlGhxnb29nbGUv",
            "cHJvdG9idWYvc3RydWN0LnByb3RvGitmZHMvcHJvdG9idWYvc3RhY2gvdjIv",
            "dGFibGUvUmVmZXJlbmNlLnByb3RvIoABCgxNZXRhZGF0YUl0ZW0SJwoFdmFs",
            "dWUYASABKAsyFi5nb29nbGUucHJvdG9idWYuVmFsdWVIABI/CglyZWZlcmVu",
            "Y2UYAiABKAsyKi5mYWN0c2V0LnByb3RvYnVmLnN0YWNoLnYyLnRhYmxlLlJl",
            "ZmVyZW5jZUgAQgYKBGRhdGFCmQEKI2NvbS5mYWN0c2V0LnByb3RvYnVmLnN0",
            "YWNoLnYyLnRhYmxlQhFNZXRhZGF0YUl0ZW1Qcm90b1o9Z2l0aHViLmNvbS9m",
            "YWN0c2V0L3N0YWNoc2NoZW1hL2dvL2Zkcy9wcm90b2J1Zi9zdGFjaC92Mi90",
            "YWJsZaoCH0ZhY3RTZXQuUHJvdG9idWYuU3RhY2guVjIuVGFibGViBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.StructReflection.Descriptor, global::FactSet.Protobuf.Stach.V2.Table.ReferenceReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::FactSet.Protobuf.Stach.V2.Table.MetadataItem), global::FactSet.Protobuf.Stach.V2.Table.MetadataItem.Parser, new[]{ "Value", "Reference" }, new[]{ "Data" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// A metadata item
  ///
  /// Represents data to describe the table or parts of the table
  /// </summary>
  public sealed partial class MetadataItem : pb::IMessage<MetadataItem> {
    private static readonly pb::MessageParser<MetadataItem> _parser = new pb::MessageParser<MetadataItem>(() => new MetadataItem());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MetadataItem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FactSet.Protobuf.Stach.V2.Table.MetadataItemReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MetadataItem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MetadataItem(MetadataItem other) : this() {
      switch (other.DataCase) {
        case DataOneofCase.Value:
          Value = other.Value.Clone();
          break;
        case DataOneofCase.Reference:
          Reference = other.Reference.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MetadataItem Clone() {
      return new MetadataItem(this);
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 1;
    /// <summary>
    /// The value
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Value Value {
      get { return dataCase_ == DataOneofCase.Value ? (global::Google.Protobuf.WellKnownTypes.Value) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Value;
      }
    }

    /// <summary>Field number for the "reference" field.</summary>
    public const int ReferenceFieldNumber = 2;
    /// <summary>
    /// The table reference
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FactSet.Protobuf.Stach.V2.Table.Reference Reference {
      get { return dataCase_ == DataOneofCase.Reference ? (global::FactSet.Protobuf.Stach.V2.Table.Reference) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Reference;
      }
    }

    private object data_;
    /// <summary>Enum of possible cases for the "data" oneof.</summary>
    public enum DataOneofCase {
      None = 0,
      Value = 1,
      Reference = 2,
    }
    private DataOneofCase dataCase_ = DataOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DataOneofCase DataCase {
      get { return dataCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearData() {
      dataCase_ = DataOneofCase.None;
      data_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MetadataItem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MetadataItem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Value, other.Value)) return false;
      if (!object.Equals(Reference, other.Reference)) return false;
      if (DataCase != other.DataCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (dataCase_ == DataOneofCase.Value) hash ^= Value.GetHashCode();
      if (dataCase_ == DataOneofCase.Reference) hash ^= Reference.GetHashCode();
      hash ^= (int) dataCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (dataCase_ == DataOneofCase.Value) {
        output.WriteRawTag(10);
        output.WriteMessage(Value);
      }
      if (dataCase_ == DataOneofCase.Reference) {
        output.WriteRawTag(18);
        output.WriteMessage(Reference);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (dataCase_ == DataOneofCase.Value) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Value);
      }
      if (dataCase_ == DataOneofCase.Reference) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Reference);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MetadataItem other) {
      if (other == null) {
        return;
      }
      switch (other.DataCase) {
        case DataOneofCase.Value:
          if (Value == null) {
            Value = new global::Google.Protobuf.WellKnownTypes.Value();
          }
          Value.MergeFrom(other.Value);
          break;
        case DataOneofCase.Reference:
          if (Reference == null) {
            Reference = new global::FactSet.Protobuf.Stach.V2.Table.Reference();
          }
          Reference.MergeFrom(other.Reference);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Google.Protobuf.WellKnownTypes.Value subBuilder = new global::Google.Protobuf.WellKnownTypes.Value();
            if (dataCase_ == DataOneofCase.Value) {
              subBuilder.MergeFrom(Value);
            }
            input.ReadMessage(subBuilder);
            Value = subBuilder;
            break;
          }
          case 18: {
            global::FactSet.Protobuf.Stach.V2.Table.Reference subBuilder = new global::FactSet.Protobuf.Stach.V2.Table.Reference();
            if (dataCase_ == DataOneofCase.Reference) {
              subBuilder.MergeFrom(Reference);
            }
            input.ReadMessage(subBuilder);
            Reference = subBuilder;
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
