// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: fds/protobuf/stach/v2/table/ReferenceType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace FactSet.Protobuf.Stach.V2.Table {

  /// <summary>Holder for reflection information generated from fds/protobuf/stach/v2/table/ReferenceType.proto</summary>
  public static partial class ReferenceTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for fds/protobuf/stach/v2/table/ReferenceType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ReferenceTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci9mZHMvcHJvdG9idWYvc3RhY2gvdjIvdGFibGUvUmVmZXJlbmNlVHlwZS5w",
            "cm90bxIfZmFjdHNldC5wcm90b2J1Zi5zdGFjaC52Mi50YWJsZSpVCg1SZWZl",
            "cmVuY2VUeXBlEhoKFlVOS05PV05fUkVGRVJFTkNFX1RZUEUQABIJCgVUQUJM",
            "RRABEgoKBkNPTFVNThACEgcKA1JPVxADEggKBENFTEwQBEKfAQojY29tLmZh",
            "Y3RzZXQucHJvdG9idWYuc3RhY2gudjIudGFibGVCElJlZmVyZW5jZVR5cGVQ",
            "cm90b1pCZ2l0aHViLmNvbS9mYWN0c2V0L3N0YWNoc2NoZW1hLXNka3MvZ28v",
            "ZmRzL3Byb3RvYnVmL3N0YWNoL3YyL3RhYmxlqgIfRmFjdFNldC5Qcm90b2J1",
            "Zi5TdGFjaC5WMi5UYWJsZWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::FactSet.Protobuf.Stach.V2.Table.ReferenceType), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// The type of table reference
  /// </summary>
  public enum ReferenceType {
    /// <summary>
    /// This value should never be used, but exists to ensure that a value is specified
    /// </summary>
    [pbr::OriginalName("UNKNOWN_REFERENCE_TYPE")] UnknownReferenceType = 0,
    /// <summary>
    /// The table reference
    /// </summary>
    [pbr::OriginalName("TABLE")] Table = 1,
    /// <summary>
    /// The column reference
    /// </summary>
    [pbr::OriginalName("COLUMN")] Column = 2,
    /// <summary>
    /// The row reference
    /// </summary>
    [pbr::OriginalName("ROW")] Row = 3,
    /// <summary>
    /// The cell reference
    /// </summary>
    [pbr::OriginalName("CELL")] Cell = 4,
  }

  #endregion

}

#endregion Designer generated code
