// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: fds/protobuf/stach/v2/table/VerticalAlignment.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace FactSet.Protobuf.Stach.V2.Table {

  /// <summary>Holder for reflection information generated from fds/protobuf/stach/v2/table/VerticalAlignment.proto</summary>
  public static partial class VerticalAlignmentReflection {

    #region Descriptor
    /// <summary>File descriptor for fds/protobuf/stach/v2/table/VerticalAlignment.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static VerticalAlignmentReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjNmZHMvcHJvdG9idWYvc3RhY2gvdjIvdGFibGUvVmVydGljYWxBbGlnbm1l",
            "bnQucHJvdG8SH2ZhY3RzZXQucHJvdG9idWYuc3RhY2gudjIudGFibGUqSAoR",
            "VmVydGljYWxBbGlnbm1lbnQSEgoOVU5LTk9XTl9WQUxJR04QABIHCgNUT1AQ",
            "ARIKCgZNSURETEUQAhIKCgZCT1RUT00QA0KeAQojY29tLmZhY3RzZXQucHJv",
            "dG9idWYuc3RhY2gudjIudGFibGVCFlZlcnRpY2FsQWxpZ25tZW50UHJvdG9a",
            "PWdpdGh1Yi5jb20vZmFjdHNldC9zdGFjaHNjaGVtYS9nby9mZHMvcHJvdG9i",
            "dWYvc3RhY2gvdjIvdGFibGWqAh9GYWN0U2V0LlByb3RvYnVmLlN0YWNoLlYy",
            "LlRhYmxlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::FactSet.Protobuf.Stach.V2.Table.VerticalAlignment), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// A vertical alignment
  /// </summary>
  public enum VerticalAlignment {
    /// <summary>
    /// This value should never be used, but exists to ensure that a value is specified
    /// </summary>
    [pbr::OriginalName("UNKNOWN_VALIGN")] UnknownValign = 0,
    /// <summary>
    /// Value is vertically aligned to the top of the cell
    /// </summary>
    [pbr::OriginalName("TOP")] Top = 1,
    /// <summary>
    /// Value is vertically aligned to the middle of the cell
    /// </summary>
    [pbr::OriginalName("MIDDLE")] Middle = 2,
    /// <summary>
    /// Value is vertically aligned to the bottom of the cell
    /// </summary>
    [pbr::OriginalName("BOTTOM")] Bottom = 3,
  }

  #endregion

}

#endregion Designer generated code
