// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: fds/protobuf/stach/MetadataItem.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace FactSet.Protobuf.Stach {

  /// <summary>Holder for reflection information generated from fds/protobuf/stach/MetadataItem.proto</summary>
  public static partial class MetadataItemReflection {

    #region Descriptor
    /// <summary>File descriptor for fds/protobuf/stach/MetadataItem.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MetadataItemReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiVmZHMvcHJvdG9idWYvc3RhY2gvTWV0YWRhdGFJdGVtLnByb3RvEhZmYWN0",
            "c2V0LnByb3RvYnVmLnN0YWNoGh5nb29nbGUvcHJvdG9idWYvZHVyYXRpb24u",
            "cHJvdG8aH2dvb2dsZS9wcm90b2J1Zi90aW1lc3RhbXAucHJvdG8aKGZkcy9w",
            "cm90b2J1Zi9zdGFjaC90YWJsZS9SZWZlcmVuY2UucHJvdG8ilQMKDE1ldGFk",
            "YXRhSXRlbRIMCgRuYW1lGAEgASgJEhYKDGRvdWJsZV92YWx1ZRhkIAEoAUgA",
            "EhUKC2Zsb2F0X3ZhbHVlGGUgASgCSAASFQoLaW50MzJfdmFsdWUYZiABKAVI",
            "ABIVCgtpbnQ2NF92YWx1ZRhnIAEoA0gAEhQKCmJvb2xfdmFsdWUYaiABKAhI",
            "ABIWCgxzdHJpbmdfdmFsdWUYayABKAlIABIzCg5kdXJhdGlvbl92YWx1ZRhs",
            "IAEoCzIZLmdvb2dsZS5wcm90b2J1Zi5EdXJhdGlvbkgAEjUKD3RpbWVzdGFt",
            "cF92YWx1ZRhtIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBIABI9",
            "CglyZWZfdmFsdWUYyQEgASgLMicuZmFjdHNldC5wcm90b2J1Zi5zdGFjaC50",
            "YWJsZS5SZWZlcmVuY2VIAEIGCgRkYXRhSgQIaBBpSgQIaRBqSgYIyAEQyQFS",
            "DHVpbnQzMl92YWx1ZVIMdWludDY0X3ZhbHVlUglhbnlfdmFsdWVCSAoaY29t",
            "LmZhY3RzZXQucHJvdG9idWYuc3RhY2hCEU1ldGFkYXRhSXRlbVByb3RvqgIW",
            "RmFjdFNldC5Qcm90b2J1Zi5TdGFjaGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.DurationReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::FactSet.Protobuf.Stach.Table.ReferenceReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::FactSet.Protobuf.Stach.MetadataItem), global::FactSet.Protobuf.Stach.MetadataItem.Parser, new[]{ "Name", "DoubleValue", "FloatValue", "Int32Value", "Int64Value", "BoolValue", "StringValue", "DurationValue", "TimestampValue", "RefValue" }, new[]{ "Data" }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class MetadataItem : pb::IMessage<MetadataItem> {
    private static readonly pb::MessageParser<MetadataItem> _parser = new pb::MessageParser<MetadataItem>(() => new MetadataItem());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MetadataItem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FactSet.Protobuf.Stach.MetadataItemReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MetadataItem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MetadataItem(MetadataItem other) : this() {
      name_ = other.name_;
      switch (other.DataCase) {
        case DataOneofCase.DoubleValue:
          DoubleValue = other.DoubleValue;
          break;
        case DataOneofCase.FloatValue:
          FloatValue = other.FloatValue;
          break;
        case DataOneofCase.Int32Value:
          Int32Value = other.Int32Value;
          break;
        case DataOneofCase.Int64Value:
          Int64Value = other.Int64Value;
          break;
        case DataOneofCase.BoolValue:
          BoolValue = other.BoolValue;
          break;
        case DataOneofCase.StringValue:
          StringValue = other.StringValue;
          break;
        case DataOneofCase.DurationValue:
          DurationValue = other.DurationValue.Clone();
          break;
        case DataOneofCase.TimestampValue:
          TimestampValue = other.TimestampValue.Clone();
          break;
        case DataOneofCase.RefValue:
          RefValue = other.RefValue.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MetadataItem Clone() {
      return new MetadataItem(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "double_value" field.</summary>
    public const int DoubleValueFieldNumber = 100;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double DoubleValue {
      get { return dataCase_ == DataOneofCase.DoubleValue ? (double) data_ : 0D; }
      set {
        data_ = value;
        dataCase_ = DataOneofCase.DoubleValue;
      }
    }

    /// <summary>Field number for the "float_value" field.</summary>
    public const int FloatValueFieldNumber = 101;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float FloatValue {
      get { return dataCase_ == DataOneofCase.FloatValue ? (float) data_ : 0F; }
      set {
        data_ = value;
        dataCase_ = DataOneofCase.FloatValue;
      }
    }

    /// <summary>Field number for the "int32_value" field.</summary>
    public const int Int32ValueFieldNumber = 102;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Int32Value {
      get { return dataCase_ == DataOneofCase.Int32Value ? (int) data_ : 0; }
      set {
        data_ = value;
        dataCase_ = DataOneofCase.Int32Value;
      }
    }

    /// <summary>Field number for the "int64_value" field.</summary>
    public const int Int64ValueFieldNumber = 103;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Int64Value {
      get { return dataCase_ == DataOneofCase.Int64Value ? (long) data_ : 0L; }
      set {
        data_ = value;
        dataCase_ = DataOneofCase.Int64Value;
      }
    }

    /// <summary>Field number for the "bool_value" field.</summary>
    public const int BoolValueFieldNumber = 106;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool BoolValue {
      get { return dataCase_ == DataOneofCase.BoolValue ? (bool) data_ : false; }
      set {
        data_ = value;
        dataCase_ = DataOneofCase.BoolValue;
      }
    }

    /// <summary>Field number for the "string_value" field.</summary>
    public const int StringValueFieldNumber = 107;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string StringValue {
      get { return dataCase_ == DataOneofCase.StringValue ? (string) data_ : ""; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        dataCase_ = DataOneofCase.StringValue;
      }
    }

    /// <summary>Field number for the "duration_value" field.</summary>
    public const int DurationValueFieldNumber = 108;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Duration DurationValue {
      get { return dataCase_ == DataOneofCase.DurationValue ? (global::Google.Protobuf.WellKnownTypes.Duration) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.DurationValue;
      }
    }

    /// <summary>Field number for the "timestamp_value" field.</summary>
    public const int TimestampValueFieldNumber = 109;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp TimestampValue {
      get { return dataCase_ == DataOneofCase.TimestampValue ? (global::Google.Protobuf.WellKnownTypes.Timestamp) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.TimestampValue;
      }
    }

    /// <summary>Field number for the "ref_value" field.</summary>
    public const int RefValueFieldNumber = 201;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FactSet.Protobuf.Stach.Table.Reference RefValue {
      get { return dataCase_ == DataOneofCase.RefValue ? (global::FactSet.Protobuf.Stach.Table.Reference) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.RefValue;
      }
    }

    private object data_;
    /// <summary>Enum of possible cases for the "data" oneof.</summary>
    public enum DataOneofCase {
      None = 0,
      DoubleValue = 100,
      FloatValue = 101,
      Int32Value = 102,
      Int64Value = 103,
      BoolValue = 106,
      StringValue = 107,
      DurationValue = 108,
      TimestampValue = 109,
      RefValue = 201,
    }
    private DataOneofCase dataCase_ = DataOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DataOneofCase DataCase {
      get { return dataCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearData() {
      dataCase_ = DataOneofCase.None;
      data_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MetadataItem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MetadataItem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(DoubleValue, other.DoubleValue)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(FloatValue, other.FloatValue)) return false;
      if (Int32Value != other.Int32Value) return false;
      if (Int64Value != other.Int64Value) return false;
      if (BoolValue != other.BoolValue) return false;
      if (StringValue != other.StringValue) return false;
      if (!object.Equals(DurationValue, other.DurationValue)) return false;
      if (!object.Equals(TimestampValue, other.TimestampValue)) return false;
      if (!object.Equals(RefValue, other.RefValue)) return false;
      if (DataCase != other.DataCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (dataCase_ == DataOneofCase.DoubleValue) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(DoubleValue);
      if (dataCase_ == DataOneofCase.FloatValue) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(FloatValue);
      if (dataCase_ == DataOneofCase.Int32Value) hash ^= Int32Value.GetHashCode();
      if (dataCase_ == DataOneofCase.Int64Value) hash ^= Int64Value.GetHashCode();
      if (dataCase_ == DataOneofCase.BoolValue) hash ^= BoolValue.GetHashCode();
      if (dataCase_ == DataOneofCase.StringValue) hash ^= StringValue.GetHashCode();
      if (dataCase_ == DataOneofCase.DurationValue) hash ^= DurationValue.GetHashCode();
      if (dataCase_ == DataOneofCase.TimestampValue) hash ^= TimestampValue.GetHashCode();
      if (dataCase_ == DataOneofCase.RefValue) hash ^= RefValue.GetHashCode();
      hash ^= (int) dataCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (dataCase_ == DataOneofCase.DoubleValue) {
        output.WriteRawTag(161, 6);
        output.WriteDouble(DoubleValue);
      }
      if (dataCase_ == DataOneofCase.FloatValue) {
        output.WriteRawTag(173, 6);
        output.WriteFloat(FloatValue);
      }
      if (dataCase_ == DataOneofCase.Int32Value) {
        output.WriteRawTag(176, 6);
        output.WriteInt32(Int32Value);
      }
      if (dataCase_ == DataOneofCase.Int64Value) {
        output.WriteRawTag(184, 6);
        output.WriteInt64(Int64Value);
      }
      if (dataCase_ == DataOneofCase.BoolValue) {
        output.WriteRawTag(208, 6);
        output.WriteBool(BoolValue);
      }
      if (dataCase_ == DataOneofCase.StringValue) {
        output.WriteRawTag(218, 6);
        output.WriteString(StringValue);
      }
      if (dataCase_ == DataOneofCase.DurationValue) {
        output.WriteRawTag(226, 6);
        output.WriteMessage(DurationValue);
      }
      if (dataCase_ == DataOneofCase.TimestampValue) {
        output.WriteRawTag(234, 6);
        output.WriteMessage(TimestampValue);
      }
      if (dataCase_ == DataOneofCase.RefValue) {
        output.WriteRawTag(202, 12);
        output.WriteMessage(RefValue);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (dataCase_ == DataOneofCase.DoubleValue) {
        size += 2 + 8;
      }
      if (dataCase_ == DataOneofCase.FloatValue) {
        size += 2 + 4;
      }
      if (dataCase_ == DataOneofCase.Int32Value) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Int32Value);
      }
      if (dataCase_ == DataOneofCase.Int64Value) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(Int64Value);
      }
      if (dataCase_ == DataOneofCase.BoolValue) {
        size += 2 + 1;
      }
      if (dataCase_ == DataOneofCase.StringValue) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(StringValue);
      }
      if (dataCase_ == DataOneofCase.DurationValue) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(DurationValue);
      }
      if (dataCase_ == DataOneofCase.TimestampValue) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(TimestampValue);
      }
      if (dataCase_ == DataOneofCase.RefValue) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(RefValue);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MetadataItem other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      switch (other.DataCase) {
        case DataOneofCase.DoubleValue:
          DoubleValue = other.DoubleValue;
          break;
        case DataOneofCase.FloatValue:
          FloatValue = other.FloatValue;
          break;
        case DataOneofCase.Int32Value:
          Int32Value = other.Int32Value;
          break;
        case DataOneofCase.Int64Value:
          Int64Value = other.Int64Value;
          break;
        case DataOneofCase.BoolValue:
          BoolValue = other.BoolValue;
          break;
        case DataOneofCase.StringValue:
          StringValue = other.StringValue;
          break;
        case DataOneofCase.DurationValue:
          if (DurationValue == null) {
            DurationValue = new global::Google.Protobuf.WellKnownTypes.Duration();
          }
          DurationValue.MergeFrom(other.DurationValue);
          break;
        case DataOneofCase.TimestampValue:
          if (TimestampValue == null) {
            TimestampValue = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          TimestampValue.MergeFrom(other.TimestampValue);
          break;
        case DataOneofCase.RefValue:
          if (RefValue == null) {
            RefValue = new global::FactSet.Protobuf.Stach.Table.Reference();
          }
          RefValue.MergeFrom(other.RefValue);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 801: {
            DoubleValue = input.ReadDouble();
            break;
          }
          case 813: {
            FloatValue = input.ReadFloat();
            break;
          }
          case 816: {
            Int32Value = input.ReadInt32();
            break;
          }
          case 824: {
            Int64Value = input.ReadInt64();
            break;
          }
          case 848: {
            BoolValue = input.ReadBool();
            break;
          }
          case 858: {
            StringValue = input.ReadString();
            break;
          }
          case 866: {
            global::Google.Protobuf.WellKnownTypes.Duration subBuilder = new global::Google.Protobuf.WellKnownTypes.Duration();
            if (dataCase_ == DataOneofCase.DurationValue) {
              subBuilder.MergeFrom(DurationValue);
            }
            input.ReadMessage(subBuilder);
            DurationValue = subBuilder;
            break;
          }
          case 874: {
            global::Google.Protobuf.WellKnownTypes.Timestamp subBuilder = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            if (dataCase_ == DataOneofCase.TimestampValue) {
              subBuilder.MergeFrom(TimestampValue);
            }
            input.ReadMessage(subBuilder);
            TimestampValue = subBuilder;
            break;
          }
          case 1610: {
            global::FactSet.Protobuf.Stach.Table.Reference subBuilder = new global::FactSet.Protobuf.Stach.Table.Reference();
            if (dataCase_ == DataOneofCase.RefValue) {
              subBuilder.MergeFrom(RefValue);
            }
            input.ReadMessage(subBuilder);
            RefValue = subBuilder;
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
