// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: fds/protobuf/stach/table/ReferenceType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace FactSet.Protobuf.Stach.Table {

  /// <summary>Holder for reflection information generated from fds/protobuf/stach/table/ReferenceType.proto</summary>
  public static partial class ReferenceTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for fds/protobuf/stach/table/ReferenceType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ReferenceTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CixmZHMvcHJvdG9idWYvc3RhY2gvdGFibGUvUmVmZXJlbmNlVHlwZS5wcm90",
            "bxIcZmFjdHNldC5wcm90b2J1Zi5zdGFjaC50YWJsZSpVCg1SZWZlcmVuY2VU",
            "eXBlEhoKFlVOS05PV05fUkVGRVJFTkNFX1RZUEUQABIJCgVUQUJMRRABEgoK",
            "BkNPTFVNThACEgcKA1JPVxADEggKBENFTEwQBEJVCiBjb20uZmFjdHNldC5w",
            "cm90b2J1Zi5zdGFjaC50YWJsZUISUmVmZXJlbmNlVHlwZVByb3RvqgIcRmFj",
            "dFNldC5Qcm90b2J1Zi5TdGFjaC5UYWJsZWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::FactSet.Protobuf.Stach.Table.ReferenceType), }, null));
    }
    #endregion

  }
  #region Enums
  public enum ReferenceType {
    [pbr::OriginalName("UNKNOWN_REFERENCE_TYPE")] UnknownReferenceType = 0,
    [pbr::OriginalName("TABLE")] Table = 1,
    [pbr::OriginalName("COLUMN")] Column = 2,
    [pbr::OriginalName("ROW")] Row = 3,
    [pbr::OriginalName("CELL")] Cell = 4,
  }

  #endregion

}

#endregion Designer generated code
