// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: fds/protobuf/stach/table/ReferenceFilterMode.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace FactSet.Protobuf.Stach.Table {

  /// <summary>Holder for reflection information generated from fds/protobuf/stach/table/ReferenceFilterMode.proto</summary>
  public static partial class ReferenceFilterModeReflection {

    #region Descriptor
    /// <summary>File descriptor for fds/protobuf/stach/table/ReferenceFilterMode.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ReferenceFilterModeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjJmZHMvcHJvdG9idWYvc3RhY2gvdGFibGUvUmVmZXJlbmNlRmlsdGVyTW9k",
            "ZS5wcm90bxIcZmFjdHNldC5wcm90b2J1Zi5zdGFjaC50YWJsZSovChNSZWZl",
            "cmVuY2VGaWx0ZXJNb2RlEgsKB0lOQ0xVREUQABILCgdFWENMVURFEAFCWwog",
            "Y29tLmZhY3RzZXQucHJvdG9idWYuc3RhY2gudGFibGVCGFJlZmVyZW5jZUZp",
            "bHRlck1vZGVQcm90b6oCHEZhY3RTZXQuUHJvdG9idWYuU3RhY2guVGFibGVi",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::FactSet.Protobuf.Stach.Table.ReferenceFilterMode), }, null));
    }
    #endregion

  }
  #region Enums
  public enum ReferenceFilterMode {
    [pbr::OriginalName("INCLUDE")] Include = 0,
    [pbr::OriginalName("EXCLUDE")] Exclude = 1,
  }

  #endregion

}

#endregion Designer generated code
