// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: fds/protobuf/stach/table/ReferenceType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace FactSet.Protobuf.Stach.Table {

  /// <summary>Holder for reflection information generated from fds/protobuf/stach/table/ReferenceType.proto</summary>
  public static partial class ReferenceTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for fds/protobuf/stach/table/ReferenceType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ReferenceTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CixmZHMvcHJvdG9idWYvc3RhY2gvdGFibGUvUmVmZXJlbmNlVHlwZS5wcm90",
            "bxIcZmFjdHNldC5wcm90b2J1Zi5zdGFjaC50YWJsZSpVCg1SZWZlcmVuY2VU",
            "eXBlEhoKFlVOS05PV05fUkVGRVJFTkNFX1RZUEUQABIJCgVUQUJMRRABEgoK",
            "BkNPTFVNThACEgcKA1JPVxADEggKBENFTEwQBEKUAQogY29tLmZhY3RzZXQu",
            "cHJvdG9idWYuc3RhY2gudGFibGVCElJlZmVyZW5jZVR5cGVQcm90b1o9Z2l0",
            "aHViLmNvbS9mYWN0c2V0L3N0YWNoc2NoZW1hL2dvL3YyL2Zkcy9wcm90b2J1",
            "Zi9zdGFjaC90YWJsZaoCHEZhY3RTZXQuUHJvdG9idWYuU3RhY2guVGFibGVi",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::FactSet.Protobuf.Stach.Table.ReferenceType), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// The type of table reference
  /// </summary>
  public enum ReferenceType {
    /// <summary>
    /// This value should never be used, but exists to ensure that a value is specified
    /// </summary>
    [pbr::OriginalName("UNKNOWN_REFERENCE_TYPE")] UnknownReferenceType = 0,
    /// <summary>
    /// The table reference
    /// </summary>
    [pbr::OriginalName("TABLE")] Table = 1,
    /// <summary>
    /// The column reference
    /// </summary>
    [pbr::OriginalName("COLUMN")] Column = 2,
    /// <summary>
    /// The row reference
    /// </summary>
    [pbr::OriginalName("ROW")] Row = 3,
    /// <summary>
    /// The cell reference
    /// </summary>
    [pbr::OriginalName("CELL")] Cell = 4,
  }

  #endregion

}

#endregion Designer generated code
