# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fds/protobuf/stach/Package.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from fds.protobuf.stach.table import Table_pb2 as fds_dot_protobuf_dot_stach_dot_table_dot_Table__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='fds/protobuf/stach/Package.proto',
  package='factset.protobuf.stach',
  syntax='proto3',
  serialized_options=_b('\n\032com.factset.protobuf.stachB\014PackageProto\252\002\026FactSet.Protobuf.Stach'),
  serialized_pb=_b('\n fds/protobuf/stach/Package.proto\x12\x16\x66\x61\x63tset.protobuf.stach\x1a$fds/protobuf/stach/table/Table.proto\"\xc6\x01\n\x07Package\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x19\n\x11primary_table_ids\x18\x02 \x03(\t\x12;\n\x06tables\x18\x03 \x03(\x0b\x32+.factset.protobuf.stach.Package.TablesEntry\x1aR\n\x0bTablesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x32\n\x05value\x18\x02 \x01(\x0b\x32#.factset.protobuf.stach.table.Table:\x02\x38\x01\x42\x43\n\x1a\x63om.factset.protobuf.stachB\x0cPackageProto\xaa\x02\x16\x46\x61\x63tSet.Protobuf.Stachb\x06proto3')
  ,
  dependencies=[fds_dot_protobuf_dot_stach_dot_table_dot_Table__pb2.DESCRIPTOR,])




_PACKAGE_TABLESENTRY = _descriptor.Descriptor(
  name='TablesEntry',
  full_name='factset.protobuf.stach.Package.TablesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='factset.protobuf.stach.Package.TablesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='factset.protobuf.stach.Package.TablesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=297,
)

_PACKAGE = _descriptor.Descriptor(
  name='Package',
  full_name='factset.protobuf.stach.Package',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='factset.protobuf.stach.Package.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='primary_table_ids', full_name='factset.protobuf.stach.Package.primary_table_ids', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tables', full_name='factset.protobuf.stach.Package.tables', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PACKAGE_TABLESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=297,
)

_PACKAGE_TABLESENTRY.fields_by_name['value'].message_type = fds_dot_protobuf_dot_stach_dot_table_dot_Table__pb2._TABLE
_PACKAGE_TABLESENTRY.containing_type = _PACKAGE
_PACKAGE.fields_by_name['tables'].message_type = _PACKAGE_TABLESENTRY
DESCRIPTOR.message_types_by_name['Package'] = _PACKAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Package = _reflection.GeneratedProtocolMessageType('Package', (_message.Message,), {

  'TablesEntry' : _reflection.GeneratedProtocolMessageType('TablesEntry', (_message.Message,), {
    'DESCRIPTOR' : _PACKAGE_TABLESENTRY,
    '__module__' : 'fds.protobuf.stach.Package_pb2'
    # @@protoc_insertion_point(class_scope:factset.protobuf.stach.Package.TablesEntry)
    })
  ,
  'DESCRIPTOR' : _PACKAGE,
  '__module__' : 'fds.protobuf.stach.Package_pb2'
  # @@protoc_insertion_point(class_scope:factset.protobuf.stach.Package)
  })
_sym_db.RegisterMessage(Package)
_sym_db.RegisterMessage(Package.TablesEntry)


DESCRIPTOR._options = None
_PACKAGE_TABLESENTRY._options = None
# @@protoc_insertion_point(module_scope)
